### ISSUE TITLE
Ojbc usage

### ISSUE THREAD

**Issue by mrhaxic** [KitchenStories/Elissa#4]
Hi..

is it possible to use this with in objective-c project?

Thanks.

**Comment by Broich** [comment]
Hi, 

to be honest I haven't tried Objective-C interoperability yet.

I will look into that within the next 48 hours and add support in case it is needed.

Thanks for your input!

**Comment by Broich** [comment]
Hi, I've pushed a new version that adds Objective-C compatibility (2.1).

**Comment by mrhaxic** [comment]
@Broich Thanks alot ..

**Comment by mrhaxic** [comment]
@Broich 

Could you give an example how to import the class in objc project ?

**Comment by Broich** [comment]
Sure!

`@import Elissa;`

Don't forget to put `use_frameworks!` in your Podfile 👍
